import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
// Vercel 빌드 한도: 45분(2700초) - Hobby/Pro/Enterprise 모두 동일
// 빌드 오버헤드(install + vite build + ssr build + server build) ~44초 예상
// 안전 마진 25% 적용 → prerender 가용 시간: ~2000초
const BUILD_START_TIME = Date.now();
const MAX_PRERENDER_SECONDS = 2000; // 안전 마진 포함 최대 허용 시간(초)
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p) => path.resolve(__dirname, p);
async function run() {
  console.log('🚀 Starting SEO-optimized pre-render (꿈해몽 338개 + 칼럼 61개 포함)...');
  
  const templatePath = toAbsolute('../client/dist/public/index.html');
  let template = fs.readFileSync(templatePath, 'utf-8');
  
  // 템플릿 마커 주입 (빌드 시 제거된 경우 대비)
  if (!template.includes('<!--app-html-->')) {
    template = template.replace('<div id="root"></div>', '<div id="root"><!--app-html--></div>');
    template = template.replace('</title>', '</title><!--app-head-->');
    template = template.replace('</body>', '<!--__REACT_QUERY_STATE__--></body>');
  }
  const serverEntryPath = toAbsolute('../client/dist/server/entry-server.js');
  const { render } = await import(pathToFileURL(serverEntryPath).href);
  
  // 프리렌더링할 주요 정적 라우트
  const staticRoutes = [
    '/', 
    '/yearly-fortune', 
    '/manselyeok', 
    '/daily-fortune', 
    '/dream',
    '/lifelong-saju',
    '/compatibility',
    '/tojeong',
    '/psychology',
    '/astrology',
    '/tarot',
    '/about',
    '/privacy',
    '/terms',
    '/family-saju',
    '/hybrid-compatibility',
    '/fortune-dictionary',
    '/lucky-lunch',
    '/contact',
    '/guide'
  ];
  
  // 칼럼 상세 페이지 라우트 (slug 기반 - 61개)
  const columnRoutes = [
  '/guide/luck-2026-daeun-change-b0d87c9e',
  '/guide/luck-fortune-breakthrough-cef1d14a',
  '/guide/fortune-flow-2026-second-half-caution-e347d445',
  '/guide/luck-room-cleaning-83c59830',
  '/guide/luck-fortune-secret-307e549f',
  '/guide/luck-fortune-signs-d70daba9',
  '/guide/saju-basic-saju-study-d9f2e703',
  '/guide/luck-life-habits-7945bc54',
  '/guide/fortune-flow-fate-magnifier-5ee9d8b5',
  '/guide/relation-golden-age-timing-86759dff',
  '/guide/money-wealth-golden-9cb42942',
  '/guide/health-body-energy-fortune-30d117b4',
  '/guide/fortune-flow-winter-to-spring-90b79a03',
  '/guide/fortune-flow-fate-spring-db760b73',
  '/guide/health-body-revival-0659b745',
  '/guide/relation-children-fortune-parent-331e43a6',
  '/guide/relation-children-education-60781ebe',
  '/guide/health-children-fortune-words-c388f667',
  '/guide/family-f16e40e9',
  '/guide/fortune-flow-late-bloom-golden-ef7596ef',
  '/guide/fortune-flow-children-blessing-late-231b77df',
  '/guide/career-career-change-b57094ba',
  '/guide/career-job-success-efcff2d4',
  '/guide/love-late-love-276233a2',
  '/guide/love-restart-love-e5d27e20',
  '/guide/fortune-flow-treasure-map-1024440d',
  '/guide/fortune-flow-late-bloom-fortune-9f61d4e0',
  '/guide/money-wealth-control-63d84616',
  '/guide/love-late-love-40s-5a0ac9d7',
  '/guide/money-empty-wallet-13d60396',
  '/guide/family-children-late-blessing-d737dc22',
  '/guide/money-self-employed-sales-c67535fb',
  '/guide/health-pyeongwan-pressure-4cef87ed',
  '/guide/family-children-conflict-045f10df',
  '/guide/career-reemployment-blocked-51b24cc7',
  '/guide/relation-jaengjae-e7afb912',
  '/guide/health-retirement-preparation-d266d217',
  '/guide/luck-new-home-moving-2ae23407',
  '/guide/love-short-relationship-097407a0',
  '/guide/money-partnership-money-c818fa3e',
  '/guide/family-children-study-c0e4bb92',
  '/guide/career-workplace-relationship-d5779d29',
  '/guide/money-inheritance-complex-caf5b63a',
  '/guide/love-marriage-boredom-f6ab0c92',
  '/guide/money-pyeonjae-f34b5d66',
  '/guide/career-startup-item-d1cb52ab',
  '/guide/family-inheritance-conflict-0440c2eb',
  '/guide/career-promotion-blocked-727184d9',
  '/guide/health-menopause-depression-ba837dd6',
  '/guide/relation-business-partner-conflict-ca1d4df6',
  '/guide/family-children-career-10175e9d',
  '/guide/money-wealth-leak-2ab03b7e',
  '/guide/relation-couple-personality-93c37cd5',
  '/guide/health-baekhosal-yangsal-b9d9fef4',
  '/guide/fortune-flow-project-failure-56c631ee',
  '/guide/relation-bad-relationship-da1a0ab3',
  '/guide/money-contract-deal-7ce3dbac',
  '/guide/fortune-flow-gossip-slander-bc420b12',
  '/guide/money-new-business-d972ab00',
  '/guide/career-exam-failure-e55e0eda',
  '/guide/family-family-communication-90b3867b',
  ];

  // 꿈해몽 개별 페이지 라우트 (338개)
  const dreamRoutes = [
  '/dream/adopting-white-puppy-dream',
  '/dream/airplane-crash-dream-warning',
  '/dream/ancestor-dressing-new-clothes-dream',
  '/dream/ancestor-giving-money-dream',
  '/dream/ancestors-smiling-dream',
  '/dream/ancient-jar-gold-coins-dream',
  '/dream/argument-person-disappearing-dream',
  '/dream/banquet-with-influential-people-dream',
  '/dream/barley-ears-field-dream',
  '/dream/bathing-in-clean-water-dream',
  '/dream/being-chased-dream-anxiety',
  '/dream/being-chased-dream-meaning',
  '/dream/being-praised-in-public',
  '/dream/being-stabbed-dream-meaning',
  '/dream/being-watched-dream-privacy-stress',
  '/dream/big-snake-wrapping-body-dream',
  '/dream/bird-singing-at-window',
  '/dream/black-cat-entering-house-dream',
  '/dream/bleeding-dream-meaning',
  '/dream/bleeding-from-wound-dream',
  '/dream/bleeding-wont-stop-dream-exhaustion',
  '/dream/blooming-flowers-field-dream',
  '/dream/body-turning-into-rock-dream',
  '/dream/boiling-cauldron-food-dream',
  '/dream/bright-light-from-sky-dream',
  '/dream/broken-glasses-blurry-vision-dream',
  '/dream/broken-mirror-dream-meaning',
  '/dream/broken-phone-dream-isolation',
  '/dream/busy-market-dream-meaning',
  '/dream/butterfly-and-flowers-dream',
  '/dream/butterfly-on-shoulder-dream',
  '/dream/calm-stream-water-dream',
  '/dream/cannot-find-toilet-dream-meaning',
  '/dream/car-brake-failure-dream-control',
  '/dream/cargo-ship-entering-port-dream',
  '/dream/carrying-torch-in-dark-dream',
  '/dream/cat-entering-house-dream-meaning',
  '/dream/catching-giant-carp-dream',
  '/dream/catching-many-fish-dream',
  '/dream/celebrity-confession-dream-meaning',
  '/dream/changing-into-clean-clothes',
  '/dream/changing-into-silk-clothes-dream',
  '/dream/choosing-books-in-bookstore',
  '/dream/cleaning-the-room-dream',
  '/dream/clear-water-filling-house-dream',
  '/dream/clear-water-flooding-house-dream',
  '/dream/climbing-mountain-peak-dream',
  '/dream/colorful-birds-in-yard-dream',
  '/dream/covered-in-poop-dream',
  '/dream/crossing-broken-bridge-dream',
  '/dream/cutting-hair-dream-meaning',
  '/dream/dancing-in-fancy-clothes-dream',
  '/dream/dating-celebrity-dream-meaning',
  '/dream/dead-person-scolding-dream-guilt',
  '/dream/deceased-ancestors-smiling-dream',
  '/dream/deceased-grandmother-smiling-dream',
  '/dream/discovering-gems-cave-dream',
  '/dream/distorted-mirror-dream-self-esteem',
  '/dream/dog-bite-dream-meaning',
  '/dream/dog-wagging-tail-dream-meaning',
  '/dream/dove-flying-peacefully-dream',
  '/dream/dragon-ascending-to-heaven-dream',
  '/dream/dragon-ascending-to-sky-dream',
  '/dream/dragon-tail-ascension-dream',
  '/dream/dream-ancestor-smiling',
  '/dream/dream-bleeding-body',
  '/dream/dream-butterflies-in-flower-garden',
  '/dream/dream-changing-into-new-clothes',
  '/dream/dream-chased-by-wolf',
  '/dream/dream-crossing-wide-river',
  '/dream/dream-dark-face-in-mirror',
  '/dream/dream-dead-person-coming-alive',
  '/dream/dream-dragon-ascending-to-heaven',
  '/dream/dream-falling-from-cliff',
  '/dream/dream-field-on-fire',
  '/dream/dream-finding-wild-ginseng',
  '/dream/dream-flowers-on-dead-tree',
  '/dream/dream-flying-in-airplane',
  '/dream/dream-giant-leading-way',
  '/dream/dream-gold-pig-entry',
  '/dream/dream-golden-key',
  '/dream/dream-golden-rice-field',
  '/dream/dream-holding-newborn-baby',
  '/dream/dream-house-full-of-pythons',
  '/dream/dream-losing-shoes-searching',
  '/dream/dream-lost-in-forest',
  '/dream/dream-money-falling-from-sky',
  '/dream/dream-mountain-top-clouds',
  '/dream/dream-moving-new-house',
  '/dream/dream-name-carved-on-rock',
  '/dream/dream-overflowing-toilet-waste',
  '/dream/dream-picking-up-jewels',
  '/dream/dream-picking-up-pearls-from-lake',
  '/dream/dream-pillar-breaking',
  '/dream/dream-rain-soaking-earth',
  '/dream/dream-rainbow-in-clear-sky',
  '/dream/dream-reconciling-with-enemy',
  '/dream/dream-red-peppers-in-field',
  '/dream/dream-riding-turtle-ocean',
  '/dream/dream-riding-whale-sea',
  '/dream/dream-shaking-hands-with-president',
  '/dream/dream-shouting-on-mountain-top',
  '/dream/dream-snake-biting-leg',
  '/dream/dream-stabbed-by-stranger',
  '/dream/dream-stuck-in-pit',
  '/dream/dream-surviving-giant-wave',
  '/dream/dream-sweet-kiss',
  '/dream/dream-teeth-falling-out',
  '/dream/dream-tiger-biting',
  '/dream/dream-treasure-ship-in-ocean',
  '/dream/dream-twinkling-stars-in-sky',
  '/dream/dream-two-suns-in-sky',
  '/dream/dream-walking-naked-confidently',
  '/dream/dream-watching-sunset',
  '/dream/dream-wearing-gold-ring',
  '/dream/dream-wearing-white-clothes',
  '/dream/dream-white-hair',
  '/dream/dreaming-clear-well-water',
  '/dream/dreaming-of-cockroaches',
  '/dream/dreaming-of-ex-boyfriend-girlfriend',
  '/dream/dreaming-of-flying-in-the-sky',
  '/dream/dreaming-of-making-mistakes-on-exam-papers',
  '/dream/dreaming-of-winning-lottery',
  '/dream/drinking-gem-dust-milky-way-dream',
  '/dream/drinking-spring-water-mountain',
  '/dream/drinking-warm-soup-dream',
  '/dream/drowning-dream-suffocation-stress',
  '/dream/dying-in-dream-rebirth',
  '/dream/eating-an-apple-dream',
  '/dream/eating-delicious-food-dream',
  '/dream/eating-gold-rice-cauldron-dream',
  '/dream/eating-sand-hair-dream-meaning',
  '/dream/elevator-up-and-down-dream-anxiety',
  '/dream/embracing-gold-dream-meaning',
  '/dream/endless-dark-tunnel-dream-despair',
  '/dream/endless-rain-grey-world-dream',
  '/dream/entering-a-cave-dream-meaning',
  '/dream/entering-palace-mansion-dream',
  '/dream/exam-failure-dream-stress',
  '/dream/face-turning-black-in-mirror-dream',
  '/dream/failing-exam-dream-meaning',
  '/dream/failing-test-dream-stress',
  '/dream/falling-dream-anxiety-interpretation',
  '/dream/falling-from-cliff-dream',
  '/dream/falling-from-high-place-dream',
  '/dream/falling-from-the-sky-dream',
  '/dream/falling-into-a-hole-dream',
  '/dream/fast-clock-dream-time-pressure',
  '/dream/feather-falling-from-sky',
  '/dream/fighting-with-friend-dream-meaning',
  '/dream/finding-gold-vein-dream',
  '/dream/finding-lost-item-dream',
  '/dream/finding-oasis-desert-dream',
  '/dream/finding-toilet-dream-emotional-release',
  '/dream/finding-wild-ginseng-dream',
  '/dream/finger-nail-pulled-out-dream',
  '/dream/floating-in-space-suffocation-dream',
  '/dream/floating-in-the-air-dream',
  '/dream/flood-house-underwater-dream',
  '/dream/flood-water-entering-house-dream',
  '/dream/flowers-over-stone-wall',
  '/dream/flying-airplane-cloud-dream',
  '/dream/flying-in-airplane-dream',
  '/dream/flying-in-airplane-dream-alt',
  '/dream/forest-fire-dream-meaning',
  '/dream/front-teeth-falling-out-dream',
  '/dream/fruit-bearing-tree-dream',
  '/dream/full-moon-in-clear-sky-dream',
  '/dream/full-moon-night-sky-dream',
  '/dream/gathering-starlight-basket-dream',
  '/dream/getting-large-bag-gift',
  '/dream/getting-lost-in-city-dream',
  '/dream/getting-lost-in-mountains-dream',
  '/dream/getting-money-from-parents',
  '/dream/getting-wet-in-rain-without-umbrella-dream',
  '/dream/getting-wet-in-the-rain-dream',
  '/dream/giant-snake-wrapping-around-body',
  '/dream/giant-wall-dream-obstacle',
  '/dream/gold-bars-under-bedroom-dream',
  '/dream/gold-dust-falling-sky-dream',
  '/dream/gold-in-clear-water-dream',
  '/dream/gold-pig-entering-house-dream',
  '/dream/gold-ring-gift-dream-meaning',
  '/dream/gold-ring-silk-pouch-dream',
  '/dream/gold-turtle-well-dream',
  '/dream/golden-carp-into-arms-dream',
  '/dream/golden-castle-rising-sea-dream',
  '/dream/golden-fish-mountain-valley-dream',
  '/dream/golden-flags-roof-dream',
  '/dream/golden-hair-shining-dream',
  '/dream/golden-key-from-old-man-dream',
  '/dream/golden-pig-dream-meaning',
  '/dream/golden-rice-field-dream',
  '/dream/golden-spider-web-living-room-dream',
  '/dream/grand-waterfall-dream-meaning',
  '/dream/growing-horns-on-head-dream',
  '/dream/growing-new-teeth-dream',
  '/dream/hair-loss-dream-stress-signal',
  '/dream/harvesting-golden-crops-dream',
  '/dream/hearing-laughter-mockery-dream',
  '/dream/heavy-rock-hanging-dream-pressure',
  '/dream/heavy-snow-dream-meaning',
  '/dream/herding-sheep-home-dream',
  '/dream/holding-a-newborn-baby-dream',
  '/dream/holding-golden-key-dream',
  '/dream/holding-hands-with-crush-dream',
  '/dream/house-fire-no-water-dream-stress',
  '/dream/house-full-of-jewels-dream',
  '/dream/house-on-fire-dream',
  '/dream/house-on-fire-dream-meaning',
  '/dream/hugging-a-stranger-dream',
  '/dream/hugging-stranger-dream-love',
  '/dream/ice-thawing-golden-carp-dream',
  '/dream/insects-crawling-dream-disgust',
  '/dream/kissing-a-stranger-dream',
  '/dream/letter-in-mailbox-dream',
  '/dream/looking-at-stars-night-sky',
  '/dream/losing-shoes-barefoot-dream',
  '/dream/losing-shoes-dream-meaning',
  '/dream/losing-teeth-dream-interpretation',
  '/dream/losing-voice-dream-speech-anxiety',
  '/dream/losing-wallet-phone-dream-anxiety',
  '/dream/lost-in-dark-forest-dream',
  '/dream/loved-one-turned-monster-dream',
  '/dream/luck-pouches-falling-sky-dream',
  '/dream/maze-dream-lost-path',
  '/dream/meeting-old-friend-talking',
  '/dream/meeting-president-dream-meaning',
  '/dream/mirror-self-reflection-dream',
  '/dream/missing-bus-or-train-dream',
  '/dream/missing-desk-at-work-dream',
  '/dream/missing-flight-dream-missed-opportunity',
  '/dream/money-falling-from-sky-dream',
  '/dream/money-leaves-field-dream',
  '/dream/money-tree-growing-dream',
  '/dream/money-turning-into-ash-dream',
  '/dream/moving-to-new-house-dream',
  '/dream/naked-in-public-dream-meaning',
  '/dream/naked-in-public-dream-social-anxiety',
  '/dream/night-view-from-mountain-top',
  '/dream/ocean-breeze-dream-meaning',
  '/dream/opening-treasure-vault-dream',
  '/dream/overflowing-toilet-dream-meaning',
  '/dream/peacock-giving-gold-feathers-dream',
  '/dream/peacock-spreading-wings-dream',
  '/dream/pearl-pouch-overflowing-dream',
  '/dream/pearls-from-palms-dream',
  '/dream/people-studying-in-library',
  '/dream/picking-golden-fruit-dream',
  '/dream/picking-red-strawberries-dream',
  '/dream/picking-shells-at-beach',
  '/dream/picking-shiny-pebbles-dream',
  '/dream/picking-up-coins-on-road',
  '/dream/picking-up-gold-coins-dream',
  '/dream/picking-up-jewelry-dream-meaning',
  '/dream/playing-with-child-dream',
  '/dream/pooped-on-dream-jackpot',
  '/dream/putting-on-makeup-dream-meaning',
  '/dream/rainbow-after-rain-dream',
  '/dream/rainbow-connected-to-home-dream',
  '/dream/reaching-mountain-peak-dream',
  '/dream/receiving-full-meal-table',
  '/dream/receiving-gemstone-gift-dream',
  '/dream/repairing-old-house-dream',
  '/dream/rescued-from-falling-into-ocean',
  '/dream/rice-overflowing-jar-dream',
  '/dream/riding-a-horse-dream-success',
  '/dream/riding-white-elephant-dream',
  '/dream/riding-white-horse-golden-field-dream',
  '/dream/rotten-food-worms-dream-meaning',
  '/dream/running-on-wide-road-dream',
  '/dream/seeing-dead-body-dream-meaning',
  '/dream/seeing-lotus-flower-pond',
  '/dream/seeing-name-on-pass-list-dream',
  '/dream/seeing-someone-bleeding-dream',
  '/dream/shadow-controlling-me-dream',
  '/dream/shaking-hands-with-president-dream',
  '/dream/shouting-mountain-top-dream',
  '/dream/shrinking-body-dream-inferiority',
  '/dream/sinkhole-dream-sudden-crisis',
  '/dream/sinking-into-sea-dream-anxiety',
  '/dream/sky-from-rooftop-dream',
  '/dream/smelling-baked-bread-dream',
  '/dream/smiling-at-mirror-dream',
  '/dream/snake-bite-dream-meaning',
  '/dream/snake-wrapping-around-body-dream',
  '/dream/snake-wrapping-body-dream',
  '/dream/snake-wrapping-body-dream-2',
  '/dream/snow-covered-field-dream',
  '/dream/snowing-all-over-world-dream',
  '/dream/spring-water-spouting-dream',
  '/dream/star-falling-into-arms-dream',
  '/dream/stepping-on-poop-dream-meaning',
  '/dream/stranger-in-the-mirror-dream',
  '/dream/stress-dream-chased-by-beast',
  '/dream/strong-thick-arms-dream',
  '/dream/stuck-in-a-pit-dream-meaning',
  '/dream/sunrise-from-sea-dream',
  '/dream/swallowing-sun-dream',
  '/dream/swimming-in-the-ocean-dream',
  '/dream/taking-cool-shower-dream',
  '/dream/talking-pet-resenting-dream',
  '/dream/tea-in-sunny-cafe-dream',
  '/dream/teeth-falling-out-dream-loss',
  '/dream/teeth-falling-out-dream-meaning',
  '/dream/tiger-entering-house-dream',
  '/dream/toad-with-gold-coins-dream',
  '/dream/torn-clothes-dream-meaning',
  '/dream/train-ride-viewing-landscape',
  '/dream/trapped-in-spider-web-dream',
  '/dream/traveling-by-airplane-dream',
  '/dream/tsunami-dream-paralysis-stress',
  '/dream/turtle-dream-meaning-longevity',
  '/dream/turtle-laying-golden-eggs-dream',
  '/dream/twin-dragons-room-dream',
  '/dream/uprooted-tree-dream-meaning',
  '/dream/voice-turning-into-noise-dream',
  '/dream/walking-green-forest-path',
  '/dream/walking-in-lush-forest-dream',
  '/dream/walking-on-rainbow-gold-clouds-dream',
  '/dream/walking-on-the-ocean-dream',
  '/dream/walking-on-the-sea-dream',
  '/dream/walking-on-white-clouds',
  '/dream/walking-park-seeing-flowers',
  '/dream/walking-with-angel-dream-meaning',
  '/dream/war-refugee-unprepared-dream',
  '/dream/waterfall-turning-into-coins-dream',
  '/dream/watering-potted-plants-dream',
  '/dream/wearing-new-shoes-walking',
  '/dream/wearing-royal-robe-dream',
  '/dream/wearing-shining-crown-dream',
  '/dream/whale-approaching-sea-dream',
  '/dream/whale-in-the-ocean-dream',
  '/dream/white-deer-guiding-jewels-dream',
  '/dream/white-hair-dream-meaning',
  '/dream/white-shining-teeth-dream',
  '/dream/white-tiger-riding-dream',
  '/dream/zombie-attack-dream-meaning',
  '/dream/catch-big-carp-clear-water-dream',
  '/dream/colorful-bird-flies-into-house-dream',
  '/dream/dark-muddy-water-dream',
  '/dream/death-dream-family-dies-corpse-dream',
  '/dream/front-tooth-falls-out-no-blood-dream',
  '/dream/golden-pig-enters-house-dream',
  '/dream/golden-poop-toilet-dream',
  '/dream/lost-road-familiar-place-dream',
  '/dream/pig-dream-lucky-money-dream',
  '/dream/poop-toilet-wealth-dream',
  '/dream/sunshine-after-rain-dream',
  '/dream/toes-grow-longer-dream',
  ];

  // 동적 라우트 (신년운세 - 연도별)
  const dynamicRoutes = [];
  for (let year = 1970; year <= 2020; year++) {
    dynamicRoutes.push(`/yearly-fortune/${year}-01-01`);
  }

  const allRoutes = [...staticRoutes, ...columnRoutes, ...dreamRoutes, ...dynamicRoutes];
  console.log(`📦 Total routes to pre-render: ${allRoutes.length}`);
  console.log(`   - 정적 라우트: ${staticRoutes.length}개`);
  console.log(`   - 칼럼: ${columnRoutes.length}개`);
  console.log(`   - 꿈해몽: ${dreamRoutes.length}개`);
  console.log(`   - 신년운세 동적: ${dynamicRoutes.length}개`);

  let successCount = 0;
  let skippedCount = 0;
  for (const url of allRoutes) {
    // Vercel 빌드 시간 초과 방지: 가용 시간 소진 시 조기 종료
    const elapsedSeconds = (Date.now() - BUILD_START_TIME) / 1000;
    if (elapsedSeconds > MAX_PRERENDER_SECONDS) {
      console.warn(`⏱️  Build time limit approaching (${elapsedSeconds.toFixed(1)}s elapsed). Stopping prerender to avoid Vercel timeout.`);
      skippedCount = allRoutes.length - successCount;
      break;
    }
    try {
      const { appHtml, head, dehydratedState } = await render({ path: url });
      
      const html = template
        .replace('<!--app-head-->', `${head.title}${head.meta}${head.link}`)
        .replace('<!--app-html-->', appHtml)
        .replace(
          '<!--__REACT_QUERY_STATE__-->',
          `<script>window.__REACT_QUERY_STATE__ = ${JSON.stringify(dehydratedState)}</script>`
        );
      // 디렉토리 기반 경로로 저장: /dream/pig-dream → dream/pig-dream/index.html
      const filePath = url === '/'
        ? toAbsolute('../client/dist/public/index.html')
        : toAbsolute(`../client/dist/public${url}/index.html`);
      
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, html);
      successCount++;
      
      if (successCount % 50 === 0) {
        console.log(`✅ Processed ${successCount}/${allRoutes.length} pages... (${elapsedSeconds.toFixed(1)}s)`);
      }
    } catch (e) {
      console.error(`❌ Failed to render ${url}:`, e.message);
    }
  }
  const totalElapsed = ((Date.now() - BUILD_START_TIME) / 1000).toFixed(1);
  console.log(`✨ Successfully pre-rendered ${successCount} pages in ${totalElapsed}s!`);
  if (skippedCount > 0) {
    console.warn(`⚠️  Skipped ${skippedCount} pages due to build time limit.`);
  }
}
run().catch(console.error);
