#!/usr/bin/env python3
"""
무운 작명소 - 대법원 인명용 한자 Supabase 적재 스크립트

실행 방법:
  pip install requests
  python3 scripts/seed-hanja.py

환경 변수:
  SUPABASE_URL      (선택, 기본값 하드코딩)
  SUPABASE_SERVICE_KEY  (필수: Supabase 대시보드 > Settings > API > service_role key)

주의:
  - service_role key는 RLS를 우회하므로 절대 클라이언트 코드에 노출하지 마세요.
  - 이 스크립트는 로컬 또는 CI 환경에서만 실행합니다.
"""

import os
import json
import requests
import time

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://vuifbmsdggnwygvgcrkj.supabase.co")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")

HEADERS = {
    "apikey": SUPABASE_SERVICE_KEY,
    "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# ──────────────────────────────────────────────
# 대법원 인명용 한자 데이터
#
# 자원오행(字源五行) 분류 기준:
#   목(木): 나무·식물·생명 관련 부수 (木, 艸, 竹, 禾 등)
#   화(火): 불·빛·열 관련 부수 (火, 日, 光 등)
#   토(土): 흙·땅·산 관련 부수 (土, 山, 田 등)
#   금(金): 금속·돌·단단함 관련 부수 (金, 石, 玉 등)
#   수(水): 물·비·강 관련 부수 (水, 氵, 雨 등)
#
# 획수: 원획수(原劃數) 기준 (변형 부수 보정 포함)
#   예) 水(4획) → 氵 부수로 쓰일 때도 원획 4획으로 계산
#       火(4획) → 灬 부수로 쓰일 때도 원획 4획으로 계산
# ──────────────────────────────────────────────

# 대법원 인명용 한자 핵심 데이터 (자주 사용되는 이름용 한자 선별)
# 실제 서비스에서는 전체 5,382자 데이터를 사용해야 합니다.
# 이 스크립트는 구조 예시이며, 전체 데이터는 별도 CSV 파일로 관리하는 것을 권장합니다.

HANJA_DATA = [
    # ── 목(木) 오행 ──────────────────────────────
    {"hanja": "木", "hangul": "목", "strokes": 4,  "element": "목", "meaning": "나무"},
    {"hanja": "林", "hangul": "림", "strokes": 8,  "element": "목", "meaning": "수풀"},
    {"hanja": "森", "hangul": "삼", "strokes": 12, "element": "목", "meaning": "빽빽한 숲"},
    {"hanja": "松", "hangul": "송", "strokes": 8,  "element": "목", "meaning": "소나무"},
    {"hanja": "柏", "hangul": "백", "strokes": 9,  "element": "목", "meaning": "잣나무"},
    {"hanja": "梅", "hangul": "매", "strokes": 11, "element": "목", "meaning": "매화나무"},
    {"hanja": "桂", "hangul": "계", "strokes": 10, "element": "목", "meaning": "계수나무"},
    {"hanja": "楠", "hangul": "남", "strokes": 13, "element": "목", "meaning": "녹나무"},
    {"hanja": "樹", "hangul": "수", "strokes": 16, "element": "목", "meaning": "나무"},
    {"hanja": "桐", "hangul": "동", "strokes": 10, "element": "목", "meaning": "오동나무"},
    {"hanja": "榮", "hangul": "영", "strokes": 14, "element": "목", "meaning": "영화롭다"},
    {"hanja": "棟", "hangul": "동", "strokes": 12, "element": "목", "meaning": "마룻대"},
    {"hanja": "植", "hangul": "식", "strokes": 12, "element": "목", "meaning": "심다"},
    {"hanja": "根", "hangul": "근", "strokes": 10, "element": "목", "meaning": "뿌리"},
    {"hanja": "枝", "hangul": "지", "strokes": 8,  "element": "목", "meaning": "가지"},
    {"hanja": "花", "hangul": "화", "strokes": 8,  "element": "목", "meaning": "꽃"},
    {"hanja": "葉", "hangul": "엽", "strokes": 13, "element": "목", "meaning": "잎"},
    {"hanja": "草", "hangul": "초", "strokes": 10, "element": "목", "meaning": "풀"},
    {"hanja": "蘭", "hangul": "란", "strokes": 21, "element": "목", "meaning": "난초"},
    {"hanja": "菊", "hangul": "국", "strokes": 12, "element": "목", "meaning": "국화"},
    {"hanja": "蓮", "hangul": "련", "strokes": 17, "element": "목", "meaning": "연꽃"},
    {"hanja": "苑", "hangul": "원", "strokes": 9,  "element": "목", "meaning": "동산"},
    {"hanja": "茂", "hangul": "무", "strokes": 9,  "element": "목", "meaning": "무성하다"},
    {"hanja": "芳", "hangul": "방", "strokes": 8,  "element": "목", "meaning": "꽃다운 향기"},
    {"hanja": "英", "hangul": "영", "strokes": 9,  "element": "목", "meaning": "꽃부리, 영웅"},
    {"hanja": "華", "hangul": "화", "strokes": 12, "element": "목", "meaning": "빛나다, 화려하다"},
    {"hanja": "竹", "hangul": "죽", "strokes": 6,  "element": "목", "meaning": "대나무"},
    {"hanja": "節", "hangul": "절", "strokes": 15, "element": "목", "meaning": "절개, 마디"},
    {"hanja": "禾", "hangul": "화", "strokes": 5,  "element": "목", "meaning": "벼"},
    {"hanja": "穗", "hangul": "수", "strokes": 17, "element": "목", "meaning": "이삭"},
    {"hanja": "秀", "hangul": "수", "strokes": 7,  "element": "목", "meaning": "빼어나다"},
    {"hanja": "稔", "hangul": "임", "strokes": 13, "element": "목", "meaning": "곡식이 익다"},
    {"hanja": "穩", "hangul": "온", "strokes": 19, "element": "목", "meaning": "온화하다, 편안하다"},
    {"hanja": "桓", "hangul": "환", "strokes": 10, "element": "목", "meaning": "굳세다"},
    {"hanja": "楨", "hangul": "정", "strokes": 13, "element": "목", "meaning": "굳건한 나무"},
    {"hanja": "橋", "hangul": "교", "strokes": 16, "element": "목", "meaning": "다리"},
    {"hanja": "樂", "hangul": "락", "strokes": 15, "element": "목", "meaning": "즐겁다"},
    {"hanja": "杰", "hangul": "걸", "strokes": 8,  "element": "목", "meaning": "뛰어나다"},
    {"hanja": "棋", "hangul": "기", "strokes": 12, "element": "목", "meaning": "바둑"},
    {"hanja": "柱", "hangul": "주", "strokes": 9,  "element": "목", "meaning": "기둥"},
    {"hanja": "栢", "hangul": "백", "strokes": 10, "element": "목", "meaning": "잣나무"},
    {"hanja": "梓", "hangul": "재", "strokes": 11, "element": "목", "meaning": "가래나무"},
    {"hanja": "楓", "hangul": "풍", "strokes": 13, "element": "목", "meaning": "단풍나무"},
    {"hanja": "橡", "hangul": "상", "strokes": 16, "element": "목", "meaning": "상수리나무"},
    {"hanja": "桑", "hangul": "상", "strokes": 10, "element": "목", "meaning": "뽕나무"},
    {"hanja": "柳", "hangul": "류", "strokes": 9,  "element": "목", "meaning": "버드나무"},
    {"hanja": "楊", "hangul": "양", "strokes": 13, "element": "목", "meaning": "버드나무"},
    {"hanja": "槿", "hangul": "근", "strokes": 15, "element": "목", "meaning": "무궁화"},
    {"hanja": "蕙", "hangul": "혜", "strokes": 16, "element": "목", "meaning": "혜초(향기로운 풀)"},
    {"hanja": "薰", "hangul": "훈", "strokes": 17, "element": "목", "meaning": "향기롭다"},
    {"hanja": "蒼", "hangul": "창", "strokes": 14, "element": "목", "meaning": "푸르다"},
    {"hanja": "翠", "hangul": "취", "strokes": 14, "element": "목", "meaning": "비취색, 푸르다"},
    {"hanja": "緑", "hangul": "록", "strokes": 14, "element": "목", "meaning": "초록빛"},
    {"hanja": "綠", "hangul": "록", "strokes": 14, "element": "목", "meaning": "초록빛"},
    {"hanja": "東", "hangul": "동", "strokes": 8,  "element": "목", "meaning": "동쪽"},
    {"hanja": "春", "hangul": "춘", "strokes": 9,  "element": "목", "meaning": "봄"},
    {"hanja": "仁", "hangul": "인", "strokes": 4,  "element": "목", "meaning": "어질다"},
    {"hanja": "善", "hangul": "선", "strokes": 12, "element": "목", "meaning": "착하다"},
    {"hanja": "德", "hangul": "덕", "strokes": 15, "element": "목", "meaning": "덕"},
    {"hanja": "義", "hangul": "의", "strokes": 13, "element": "목", "meaning": "의롭다"},
    {"hanja": "信", "hangul": "신", "strokes": 9,  "element": "목", "meaning": "믿음"},
    {"hanja": "誠", "hangul": "성", "strokes": 14, "element": "목", "meaning": "정성"},
    {"hanja": "孝", "hangul": "효", "strokes": 7,  "element": "목", "meaning": "효도"},
    {"hanja": "弘", "hangul": "홍", "strokes": 5,  "element": "목", "meaning": "크다, 넓다"},
    {"hanja": "博", "hangul": "박", "strokes": 12, "element": "목", "meaning": "넓다, 박식하다"},
    {"hanja": "廣", "hangul": "광", "strokes": 15, "element": "목", "meaning": "넓다"},
    {"hanja": "遠", "hangul": "원", "strokes": 14, "element": "목", "meaning": "멀다"},
    {"hanja": "長", "hangul": "장", "strokes": 8,  "element": "목", "meaning": "길다, 어른"},
    {"hanja": "大", "hangul": "대", "strokes": 3,  "element": "목", "meaning": "크다"},
    {"hanja": "偉", "hangul": "위", "strokes": 11, "element": "목", "meaning": "위대하다"},
    {"hanja": "雄", "hangul": "웅", "strokes": 12, "element": "목", "meaning": "수컷, 웅장하다"},
    {"hanja": "俊", "hangul": "준", "strokes": 9,  "element": "목", "meaning": "준수하다"},
    {"hanja": "傑", "hangul": "걸", "strokes": 12, "element": "목", "meaning": "뛰어나다"},
    {"hanja": "豪", "hangul": "호", "strokes": 14, "element": "목", "meaning": "호걸"},
    {"hanja": "賢", "hangul": "현", "strokes": 15, "element": "목", "meaning": "어질고 현명하다"},
    {"hanja": "哲", "hangul": "철", "strokes": 10, "element": "목", "meaning": "밝고 슬기롭다"},
    {"hanja": "智", "hangul": "지", "strokes": 12, "element": "목", "meaning": "지혜"},
    {"hanja": "慧", "hangul": "혜", "strokes": 15, "element": "목", "meaning": "슬기롭다"},
    {"hanja": "敏", "hangul": "민", "strokes": 11, "element": "목", "meaning": "민첩하다"},
    {"hanja": "聰", "hangul": "총", "strokes": 17, "element": "목", "meaning": "총명하다"},
    {"hanja": "明", "hangul": "명", "strokes": 8,  "element": "목", "meaning": "밝다"},
    {"hanja": "睿", "hangul": "예", "strokes": 14, "element": "목", "meaning": "슬기롭다"},
    {"hanja": "勇", "hangul": "용", "strokes": 9,  "element": "목", "meaning": "용감하다"},
    {"hanja": "健", "hangul": "건", "strokes": 11, "element": "목", "meaning": "건강하다"},
    {"hanja": "强", "hangul": "강", "strokes": 11, "element": "목", "meaning": "강하다"},
    {"hanja": "毅", "hangul": "의", "strokes": 15, "element": "목", "meaning": "굳세다"},
    {"hanja": "堅", "hangul": "견", "strokes": 11, "element": "목", "meaning": "굳다"},
    {"hanja": "志", "hangul": "지", "strokes": 7,  "element": "목", "meaning": "뜻, 의지"},
    {"hanja": "勤", "hangul": "근", "strokes": 13, "element": "목", "meaning": "부지런하다"},
    {"hanja": "勉", "hangul": "면", "strokes": 9,  "element": "목", "meaning": "힘쓰다"},
    {"hanja": "進", "hangul": "진", "strokes": 12, "element": "목", "meaning": "나아가다"},
    {"hanja": "成", "hangul": "성", "strokes": 7,  "element": "목", "meaning": "이루다"},
    {"hanja": "達", "hangul": "달", "strokes": 13, "element": "목", "meaning": "통달하다"},
    {"hanja": "昇", "hangul": "승", "strokes": 8,  "element": "목", "meaning": "오르다"},
    {"hanja": "興", "hangul": "흥", "strokes": 16, "element": "목", "meaning": "일어나다, 흥하다"},
    {"hanja": "旺", "hangul": "왕", "strokes": 8,  "element": "목", "meaning": "왕성하다"},
    {"hanja": "盛", "hangul": "성", "strokes": 12, "element": "목", "meaning": "성하다"},
    {"hanja": "昌", "hangul": "창", "strokes": 8,  "element": "목", "meaning": "번창하다"},
    {"hanja": "亨", "hangul": "형", "strokes": 7,  "element": "목", "meaning": "형통하다"},
    {"hanja": "泰", "hangul": "태", "strokes": 10, "element": "목", "meaning": "크다, 평안하다"},
    {"hanja": "安", "hangul": "안", "strokes": 6,  "element": "목", "meaning": "편안하다"},
    {"hanja": "寧", "hangul": "녕", "strokes": 14, "element": "목", "meaning": "편안하다"},
    {"hanja": "康", "hangul": "강", "strokes": 11, "element": "목", "meaning": "편안하다"},
    {"hanja": "福", "hangul": "복", "strokes": 14, "element": "목", "meaning": "복"},
    {"hanja": "祿", "hangul": "록", "strokes": 13, "element": "목", "meaning": "녹봉, 복"},
    {"hanja": "壽", "hangul": "수", "strokes": 14, "element": "목", "meaning": "장수"},
    {"hanja": "富", "hangul": "부", "strokes": 12, "element": "목", "meaning": "부유하다"},
    {"hanja": "貴", "hangul": "귀", "strokes": 12, "element": "목", "meaning": "귀하다"},
    {"hanja": "榮", "hangul": "영", "strokes": 14, "element": "목", "meaning": "영화롭다"},
    {"hanja": "顯", "hangul": "현", "strokes": 23, "element": "목", "meaning": "나타나다, 빛나다"},
    {"hanja": "揚", "hangul": "양", "strokes": 12, "element": "목", "meaning": "날리다, 드날리다"},
    {"hanja": "名", "hangul": "명", "strokes": 6,  "element": "목", "meaning": "이름, 명성"},
    {"hanja": "聲", "hangul": "성", "strokes": 17, "element": "목", "meaning": "소리, 명성"},
    {"hanja": "譽", "hangul": "예", "strokes": 21, "element": "목", "meaning": "명예"},
    {"hanja": "望", "hangul": "망", "strokes": 11, "element": "목", "meaning": "바라다, 명망"},
    {"hanja": "希", "hangul": "희", "strokes": 7,  "element": "목", "meaning": "바라다"},
    {"hanja": "願", "hangul": "원", "strokes": 19, "element": "목", "meaning": "원하다"},
    {"hanja": "夢", "hangul": "몽", "strokes": 14, "element": "목", "meaning": "꿈"},
    {"hanja": "理", "hangul": "리", "strokes": 11, "element": "목", "meaning": "이치, 다스리다"},
    {"hanja": "道", "hangul": "도", "strokes": 13, "element": "목", "meaning": "길, 도리"},
    {"hanja": "學", "hangul": "학", "strokes": 16, "element": "목", "meaning": "배우다"},
    {"hanja": "文", "hangul": "문", "strokes": 4,  "element": "목", "meaning": "글, 문화"},
    {"hanja": "武", "hangul": "무", "strokes": 8,  "element": "목", "meaning": "무예, 용맹"},
    {"hanja": "藝", "hangul": "예", "strokes": 19, "element": "목", "meaning": "재주, 예술"},
    {"hanja": "才", "hangul": "재", "strokes": 3,  "element": "목", "meaning": "재주"},
    {"hanja": "能", "hangul": "능", "strokes": 10, "element": "목", "meaning": "능하다"},
    {"hanja": "秉", "hangul": "병", "strokes": 8,  "element": "목", "meaning": "잡다, 지키다"},
    {"hanja": "相", "hangul": "상", "strokes": 9,  "element": "목", "meaning": "서로, 재상"},
    {"hanja": "輔", "hangul": "보", "strokes": 14, "element": "목", "meaning": "돕다"},
    {"hanja": "弼", "hangul": "필", "strokes": 12, "element": "목", "meaning": "돕다"},
    {"hanja": "佐", "hangul": "좌", "strokes": 7,  "element": "목", "meaning": "돕다"},
    {"hanja": "翼", "hangul": "익", "strokes": 17, "element": "목", "meaning": "날개, 돕다"},
    {"hanja": "贊", "hangul": "찬", "strokes": 19, "element": "목", "meaning": "돕다, 기리다"},
    {"hanja": "協", "hangul": "협", "strokes": 8,  "element": "목", "meaning": "화합하다"},
    {"hanja": "和", "hangul": "화", "strokes": 8,  "element": "목", "meaning": "화목하다"},
    {"hanja": "睦", "hangul": "목", "strokes": 13, "element": "목", "meaning": "화목하다"},
    {"hanja": "親", "hangul": "친", "strokes": 16, "element": "목", "meaning": "친하다"},
    {"hanja": "愛", "hangul": "애", "strokes": 13, "element": "목", "meaning": "사랑"},
    {"hanja": "慈", "hangul": "자", "strokes": 13, "element": "목", "meaning": "사랑하다"},
    {"hanja": "孜", "hangul": "자", "strokes": 7,  "element": "목", "meaning": "부지런하다"},
    {"hanja": "恩", "hangul": "은", "strokes": 10, "element": "목", "meaning": "은혜"},
    {"hanja": "惠", "hangul": "혜", "strokes": 12, "element": "목", "meaning": "은혜, 슬기"},
    {"hanja": "澤", "hangul": "택", "strokes": 17, "element": "목", "meaning": "은택, 연못"},
    {"hanja": "恒", "hangul": "항", "strokes": 9,  "element": "목", "meaning": "항상"},
    {"hanja": "常", "hangul": "상", "strokes": 11, "element": "목", "meaning": "항상, 보통"},
    {"hanja": "永", "hangul": "영", "strokes": 5,  "element": "목", "meaning": "영원하다"},
    {"hanja": "久", "hangul": "구", "strokes": 3,  "element": "목", "meaning": "오래다"},
    {"hanja": "悠", "hangul": "유", "strokes": 11, "element": "목", "meaning": "멀다, 유유하다"},
    {"hanja": "悅", "hangul": "열", "strokes": 10, "element": "목", "meaning": "기쁘다"},
    {"hanja": "喜", "hangul": "희", "strokes": 12, "element": "목", "meaning": "기쁘다"},
    {"hanja": "歡", "hangul": "환", "strokes": 22, "element": "목", "meaning": "기쁘다"},
    {"hanja": "慶", "hangul": "경", "strokes": 15, "element": "목", "meaning": "경사"},
    {"hanja": "祥", "hangul": "상", "strokes": 11, "element": "목", "meaning": "상서롭다"},
    {"hanja": "瑞", "hangul": "서", "strokes": 13, "element": "목", "meaning": "상서롭다"},
    {"hanja": "吉", "hangul": "길", "strokes": 6,  "element": "목", "meaning": "길하다"},
    {"hanja": "昭", "hangul": "소", "strokes": 9,  "element": "목", "meaning": "밝다"},
    {"hanja": "炫", "hangul": "현", "strokes": 9,  "element": "목", "meaning": "빛나다"},
    {"hanja": "燦", "hangul": "찬", "strokes": 17, "element": "목", "meaning": "빛나다"},
    {"hanja": "彬", "hangul": "빈", "strokes": 11, "element": "목", "meaning": "빛나다, 문채 나다"},
    {"hanja": "彦", "hangul": "언", "strokes": 9,  "element": "목", "meaning": "선비, 재주 있는 사람"},
    {"hanja": "俠", "hangul": "협", "strokes": 9,  "element": "목", "meaning": "의협심"},
    {"hanja": "廉", "hangul": "렴", "strokes": 13, "element": "목", "meaning": "청렴하다"},
    {"hanja": "潔", "hangul": "결", "strokes": 16, "element": "목", "meaning": "깨끗하다"},
    {"hanja": "淸", "hangul": "청", "strokes": 12, "element": "목", "meaning": "맑다"},
    {"hanja": "純", "hangul": "순", "strokes": 10, "element": "목", "meaning": "순수하다"},
    {"hanja": "眞", "hangul": "진", "strokes": 10, "element": "목", "meaning": "참되다"},
    {"hanja": "正", "hangul": "정", "strokes": 5,  "element": "목", "meaning": "바르다"},
    {"hanja": "直", "hangul": "직", "strokes": 8,  "element": "목", "meaning": "곧다"},
    {"hanja": "剛", "hangul": "강", "strokes": 10, "element": "목", "meaning": "굳세다"},
    {"hanja": "烈", "hangul": "열", "strokes": 10, "element": "목", "meaning": "세차다, 굳세다"},
    {"hanja": "節", "hangul": "절", "strokes": 15, "element": "목", "meaning": "절개"},
    {"hanja": "操", "hangul": "조", "strokes": 16, "element": "목", "meaning": "지조"},
    {"hanja": "忠", "hangul": "충", "strokes": 8,  "element": "목", "meaning": "충성"},
    {"hanja": "貞", "hangul": "정", "strokes": 9,  "element": "목", "meaning": "곧다, 정절"},
    {"hanja": "淑", "hangul": "숙", "strokes": 12, "element": "목", "meaning": "맑다, 착하다"},
    {"hanja": "雅", "hangul": "아", "strokes": 12, "element": "목", "meaning": "우아하다"},
    {"hanja": "婉", "hangul": "완", "strokes": 11, "element": "목", "meaning": "아름답다"},
    {"hanja": "媛", "hangul": "원", "strokes": 12, "element": "목", "meaning": "아름다운 여자"},
    {"hanja": "娟", "hangul": "연", "strokes": 10, "element": "목", "meaning": "아름답다"},
    {"hanja": "姸", "hangul": "연", "strokes": 9,  "element": "목", "meaning": "아름답다"},
    {"hanja": "妍", "hangul": "연", "strokes": 7,  "element": "목", "meaning": "고울 연"},
    {"hanja": "嫻", "hangul": "한", "strokes": 15, "element": "목", "meaning": "우아하다"},
    {"hanja": "嬌", "hangul": "교", "strokes": 15, "element": "목", "meaning": "아리땁다"},
    {"hanja": "婷", "hangul": "정", "strokes": 12, "element": "목", "meaning": "아름답다"},
    {"hanja": "玟", "hangul": "민", "strokes": 8,  "element": "목", "meaning": "아름다운 옥"},

    # ── 화(火) 오행 ──────────────────────────────
    {"hanja": "火", "hangul": "화", "strokes": 4,  "element": "화", "meaning": "불"},
    {"hanja": "炎", "hangul": "염", "strokes": 8,  "element": "화", "meaning": "불꽃"},
    {"hanja": "燃", "hangul": "연", "strokes": 16, "element": "화", "meaning": "타오르다"},
    {"hanja": "煥", "hangul": "환", "strokes": 13, "element": "화", "meaning": "빛나다"},
    {"hanja": "炳", "hangul": "병", "strokes": 9,  "element": "화", "meaning": "밝다"},
    {"hanja": "熙", "hangul": "희", "strokes": 13, "element": "화", "meaning": "빛나다, 화창하다"},
    {"hanja": "煜", "hangul": "욱", "strokes": 13, "element": "화", "meaning": "빛나다"},
    {"hanja": "燁", "hangul": "엽", "strokes": 16, "element": "화", "meaning": "빛나다"},
    {"hanja": "燦", "hangul": "찬", "strokes": 17, "element": "화", "meaning": "빛나다"},
    {"hanja": "燻", "hangul": "훈", "strokes": 18, "element": "화", "meaning": "연기, 향기"},
    {"hanja": "日", "hangul": "일", "strokes": 4,  "element": "화", "meaning": "해, 날"},
    {"hanja": "旭", "hangul": "욱", "strokes": 6,  "element": "화", "meaning": "아침 해"},
    {"hanja": "晨", "hangul": "신", "strokes": 11, "element": "화", "meaning": "새벽"},
    {"hanja": "曉", "hangul": "효", "strokes": 16, "element": "화", "meaning": "새벽"},
    {"hanja": "晴", "hangul": "청", "strokes": 12, "element": "화", "meaning": "맑다"},
    {"hanja": "暉", "hangul": "휘", "strokes": 13, "element": "화", "meaning": "햇빛"},
    {"hanja": "曜", "hangul": "요", "strokes": 18, "element": "화", "meaning": "빛나다"},
    {"hanja": "昱", "hangul": "욱", "strokes": 9,  "element": "화", "meaning": "밝다"},
    {"hanja": "晃", "hangul": "황", "strokes": 10, "element": "화", "meaning": "밝다"},
    {"hanja": "晧", "hangul": "호", "strokes": 11, "element": "화", "meaning": "밝다"},
    {"hanja": "皓", "hangul": "호", "strokes": 12, "element": "화", "meaning": "희다, 밝다"},
    {"hanja": "昊", "hangul": "호", "strokes": 8,  "element": "화", "meaning": "하늘"},
    {"hanja": "晟", "hangul": "성", "strokes": 11, "element": "화", "meaning": "밝다"},
    {"hanja": "暢", "hangul": "창", "strokes": 14, "element": "화", "meaning": "통하다, 화창하다"},
    {"hanja": "昺", "hangul": "병", "strokes": 9,  "element": "화", "meaning": "밝다"},
    {"hanja": "炫", "hangul": "현", "strokes": 9,  "element": "화", "meaning": "빛나다"},
    {"hanja": "烋", "hangul": "휴", "strokes": 10, "element": "화", "meaning": "아름답다"},
    {"hanja": "熹", "hangul": "희", "strokes": 16, "element": "화", "meaning": "빛나다"},
    {"hanja": "燮", "hangul": "섭", "strokes": 17, "element": "화", "meaning": "화합하다"},
    {"hanja": "光", "hangul": "광", "strokes": 6,  "element": "화", "meaning": "빛"},
    {"hanja": "輝", "hangul": "휘", "strokes": 15, "element": "화", "meaning": "빛나다"},
    {"hanja": "赫", "hangul": "혁", "strokes": 14, "element": "화", "meaning": "빛나다, 혁혁하다"},
    {"hanja": "炅", "hangul": "경", "strokes": 8,  "element": "화", "meaning": "빛나다"},
    {"hanja": "熊", "hangul": "웅", "strokes": 14, "element": "화", "meaning": "곰, 웅장하다"},
    {"hanja": "南", "hangul": "남", "strokes": 9,  "element": "화", "meaning": "남쪽"},
    {"hanja": "夏", "hangul": "하", "strokes": 10, "element": "화", "meaning": "여름"},
    {"hanja": "禮", "hangul": "례", "strokes": 18, "element": "화", "meaning": "예도"},
    {"hanja": "敬", "hangul": "경", "strokes": 13, "element": "화", "meaning": "공경하다"},
    {"hanja": "恭", "hangul": "공", "strokes": 10, "element": "화", "meaning": "공손하다"},
    {"hanja": "謙", "hangul": "겸", "strokes": 17, "element": "화", "meaning": "겸손하다"},
    {"hanja": "讓", "hangul": "양", "strokes": 24, "element": "화", "meaning": "사양하다"},
    {"hanja": "溫", "hangul": "온", "strokes": 13, "element": "화", "meaning": "따뜻하다"},
    {"hanja": "暖", "hangul": "난", "strokes": 13, "element": "화", "meaning": "따뜻하다"},
    {"hanja": "熱", "hangul": "열", "strokes": 15, "element": "화", "meaning": "뜨겁다"},
    {"hanja": "炤", "hangul": "소", "strokes": 9,  "element": "화", "meaning": "밝다"},
    {"hanja": "炘", "hangul": "흔", "strokes": 8,  "element": "화", "meaning": "빛나다"},
    {"hanja": "烔", "hangul": "동", "strokes": 10, "element": "화", "meaning": "빛나다"},
    {"hanja": "焄", "hangul": "훈", "strokes": 11, "element": "화", "meaning": "향기롭다"},
    {"hanja": "煊", "hangul": "훤", "strokes": 13, "element": "화", "meaning": "빛나다"},
    {"hanja": "熔", "hangul": "용", "strokes": 14, "element": "화", "meaning": "녹이다"},
    {"hanja": "燈", "hangul": "등", "strokes": 16, "element": "화", "meaning": "등불"},
    {"hanja": "燿", "hangul": "요", "strokes": 18, "element": "화", "meaning": "빛나다"},
    {"hanja": "曦", "hangul": "희", "strokes": 20, "element": "화", "meaning": "햇빛"},
    {"hanja": "彰", "hangul": "창", "strokes": 14, "element": "화", "meaning": "드러나다"},
    {"hanja": "炡", "hangul": "정", "strokes": 9,  "element": "화", "meaning": "빛나다"},
    {"hanja": "烈", "hangul": "열", "strokes": 10, "element": "화", "meaning": "세차다"},
    {"hanja": "焰", "hangul": "염", "strokes": 12, "element": "화", "meaning": "불꽃"},
    {"hanja": "煌", "hangul": "황", "strokes": 13, "element": "화", "meaning": "빛나다"},
    {"hanja": "熾", "hangul": "치", "strokes": 16, "element": "화", "meaning": "성하다"},
    {"hanja": "燎", "hangul": "료", "strokes": 16, "element": "화", "meaning": "횃불"},
    {"hanja": "爀", "hangul": "혁", "strokes": 20, "element": "화", "meaning": "빛나다"},
    {"hanja": "爍", "hangul": "삭", "strokes": 20, "element": "화", "meaning": "빛나다"},
    {"hanja": "爛", "hangul": "란", "strokes": 21, "element": "화", "meaning": "빛나다"},

    # ── 토(土) 오행 ──────────────────────────────
    {"hanja": "土", "hangul": "토", "strokes": 3,  "element": "토", "meaning": "흙"},
    {"hanja": "地", "hangul": "지", "strokes": 6,  "element": "토", "meaning": "땅"},
    {"hanja": "坤", "hangul": "곤", "strokes": 8,  "element": "토", "meaning": "땅, 곤괘"},
    {"hanja": "基", "hangul": "기", "strokes": 11, "element": "토", "meaning": "기초"},
    {"hanja": "培", "hangul": "배", "strokes": 11, "element": "토", "meaning": "북돋우다"},
    {"hanja": "城", "hangul": "성", "strokes": 10, "element": "토", "meaning": "성"},
    {"hanja": "垣", "hangul": "원", "strokes": 9,  "element": "토", "meaning": "담"},
    {"hanja": "域", "hangul": "역", "strokes": 11, "element": "토", "meaning": "지역"},
    {"hanja": "境", "hangul": "경", "strokes": 14, "element": "토", "meaning": "경계"},
    {"hanja": "坦", "hangul": "탄", "strokes": 8,  "element": "토", "meaning": "평탄하다"},
    {"hanja": "均", "hangul": "균", "strokes": 7,  "element": "토", "meaning": "고르다"},
    {"hanja": "平", "hangul": "평", "strokes": 5,  "element": "토", "meaning": "평평하다"},
    {"hanja": "山", "hangul": "산", "strokes": 3,  "element": "토", "meaning": "산"},
    {"hanja": "峻", "hangul": "준", "strokes": 10, "element": "토", "meaning": "높고 험하다"},
    {"hanja": "嶽", "hangul": "악", "strokes": 17, "element": "토", "meaning": "큰 산"},
    {"hanja": "岳", "hangul": "악", "strokes": 8,  "element": "토", "meaning": "큰 산"},
    {"hanja": "崇", "hangul": "숭", "strokes": 11, "element": "토", "meaning": "높다, 숭상하다"},
    {"hanja": "嵩", "hangul": "숭", "strokes": 13, "element": "토", "meaning": "높은 산"},
    {"hanja": "峰", "hangul": "봉", "strokes": 10, "element": "토", "meaning": "봉우리"},
    {"hanja": "岡", "hangul": "강", "strokes": 8,  "element": "토", "meaning": "언덕"},
    {"hanja": "丘", "hangul": "구", "strokes": 5,  "element": "토", "meaning": "언덕"},
    {"hanja": "陵", "hangul": "릉", "strokes": 11, "element": "토", "meaning": "언덕"},
    {"hanja": "原", "hangul": "원", "strokes": 10, "element": "토", "meaning": "언덕, 들"},
    {"hanja": "野", "hangul": "야", "strokes": 11, "element": "토", "meaning": "들"},
    {"hanja": "田", "hangul": "전", "strokes": 5,  "element": "토", "meaning": "밭"},
    {"hanja": "園", "hangul": "원", "strokes": 13, "element": "토", "meaning": "동산"},
    {"hanja": "坪", "hangul": "평", "strokes": 8,  "element": "토", "meaning": "평지"},
    {"hanja": "塵", "hangul": "진", "strokes": 14, "element": "토", "meaning": "먼지"},
    {"hanja": "埈", "hangul": "준", "strokes": 10, "element": "토", "meaning": "높다"},
    {"hanja": "堯", "hangul": "요", "strokes": 12, "element": "토", "meaning": "높다, 요임금"},
    {"hanja": "堤", "hangul": "제", "strokes": 12, "element": "토", "meaning": "둑"},
    {"hanja": "塔", "hangul": "탑", "strokes": 13, "element": "토", "meaning": "탑"},
    {"hanja": "壇", "hangul": "단", "strokes": 16, "element": "토", "meaning": "단"},
    {"hanja": "壁", "hangul": "벽", "strokes": 16, "element": "토", "meaning": "벽"},
    {"hanja": "中", "hangul": "중", "strokes": 4,  "element": "토", "meaning": "가운데"},
    {"hanja": "央", "hangul": "앙", "strokes": 5,  "element": "토", "meaning": "가운데"},
    {"hanja": "仲", "hangul": "중", "strokes": 6,  "element": "토", "meaning": "가운데"},
    {"hanja": "重", "hangul": "중", "strokes": 9,  "element": "토", "meaning": "무겁다, 중요하다"},
    {"hanja": "厚", "hangul": "후", "strokes": 9,  "element": "토", "meaning": "두텁다"},
    {"hanja": "篤", "hangul": "독", "strokes": 16, "element": "토", "meaning": "도탑다"},
    {"hanja": "信", "hangul": "신", "strokes": 9,  "element": "토", "meaning": "믿음"},
    {"hanja": "實", "hangul": "실", "strokes": 14, "element": "토", "meaning": "열매, 실제"},
    {"hanja": "誠", "hangul": "성", "strokes": 14, "element": "토", "meaning": "정성"},
    {"hanja": "敦", "hangul": "돈", "strokes": 12, "element": "토", "meaning": "도탑다"},
    {"hanja": "樸", "hangul": "박", "strokes": 16, "element": "토", "meaning": "순박하다"},
    {"hanja": "質", "hangul": "질", "strokes": 15, "element": "토", "meaning": "바탕, 품질"},
    {"hanja": "素", "hangul": "소", "strokes": 10, "element": "토", "meaning": "바탕, 흰색"},
    {"hanja": "本", "hangul": "본", "strokes": 5,  "element": "토", "meaning": "근본"},
    {"hanja": "元", "hangul": "원", "strokes": 4,  "element": "토", "meaning": "으뜸"},
    {"hanja": "始", "hangul": "시", "strokes": 8,  "element": "토", "meaning": "시작하다"},
    {"hanja": "初", "hangul": "초", "strokes": 7,  "element": "토", "meaning": "처음"},
    {"hanja": "源", "hangul": "원", "strokes": 13, "element": "토", "meaning": "근원"},
    {"hanja": "宗", "hangul": "종", "strokes": 8,  "element": "토", "meaning": "마루, 으뜸"},
    {"hanja": "祖", "hangul": "조", "strokes": 10, "element": "토", "meaning": "조상"},
    {"hanja": "先", "hangul": "선", "strokes": 6,  "element": "토", "meaning": "먼저"},
    {"hanja": "古", "hangul": "고", "strokes": 5,  "element": "토", "meaning": "옛날"},
    {"hanja": "典", "hangul": "전", "strokes": 8,  "element": "토", "meaning": "법, 전범"},
    {"hanja": "範", "hangul": "범", "strokes": 15, "element": "토", "meaning": "본보기"},
    {"hanja": "模", "hangul": "모", "strokes": 14, "element": "토", "meaning": "본보기"},
    {"hanja": "準", "hangul": "준", "strokes": 13, "element": "토", "meaning": "기준"},
    {"hanja": "規", "hangul": "규", "strokes": 11, "element": "토", "meaning": "법칙"},
    {"hanja": "則", "hangul": "칙", "strokes": 9,  "element": "토", "meaning": "법칙"},
    {"hanja": "法", "hangul": "법", "strokes": 9,  "element": "토", "meaning": "법"},
    {"hanja": "制", "hangul": "제", "strokes": 8,  "element": "토", "meaning": "제도"},
    {"hanja": "度", "hangul": "도", "strokes": 9,  "element": "토", "meaning": "법도"},
    {"hanja": "禮", "hangul": "례", "strokes": 18, "element": "토", "meaning": "예도"},
    {"hanja": "儀", "hangul": "의", "strokes": 15, "element": "토", "meaning": "의식"},
    {"hanja": "廉", "hangul": "렴", "strokes": 13, "element": "토", "meaning": "청렴하다"},
    {"hanja": "恪", "hangul": "각", "strokes": 9,  "element": "토", "meaning": "삼가다"},
    {"hanja": "謹", "hangul": "근", "strokes": 18, "element": "토", "meaning": "삼가다"},
    {"hanja": "愼", "hangul": "신", "strokes": 13, "element": "토", "meaning": "삼가다"},
    {"hanja": "慎", "hangul": "신", "strokes": 13, "element": "토", "meaning": "삼가다"},
    {"hanja": "穩", "hangul": "온", "strokes": 19, "element": "토", "meaning": "온화하다"},
    {"hanja": "靜", "hangul": "정", "strokes": 16, "element": "토", "meaning": "고요하다"},
    {"hanja": "寂", "hangul": "적", "strokes": 11, "element": "토", "meaning": "고요하다"},
    {"hanja": "幽", "hangul": "유", "strokes": 9,  "element": "토", "meaning": "그윽하다"},
    {"hanja": "雅", "hangul": "아", "strokes": 12, "element": "토", "meaning": "우아하다"},
    {"hanja": "淡", "hangul": "담", "strokes": 12, "element": "토", "meaning": "담백하다"},
    {"hanja": "恬", "hangul": "염", "strokes": 9,  "element": "토", "meaning": "고요하다"},
    {"hanja": "泰", "hangul": "태", "strokes": 10, "element": "토", "meaning": "크다, 평안하다"},
    {"hanja": "寬", "hangul": "관", "strokes": 15, "element": "토", "meaning": "너그럽다"},
    {"hanja": "容", "hangul": "용", "strokes": 10, "element": "토", "meaning": "용납하다"},
    {"hanja": "包", "hangul": "포", "strokes": 5,  "element": "토", "meaning": "싸다, 포용하다"},
    {"hanja": "涵", "hangul": "함", "strokes": 12, "element": "토", "meaning": "담그다, 포용하다"},
    {"hanja": "容", "hangul": "용", "strokes": 10, "element": "토", "meaning": "얼굴, 용납하다"},
    {"hanja": "態", "hangul": "태", "strokes": 14, "element": "토", "meaning": "모양"},
    {"hanja": "姿", "hangul": "자", "strokes": 9,  "element": "토", "meaning": "모양"},
    {"hanja": "儒", "hangul": "유", "strokes": 16, "element": "토", "meaning": "선비"},
    {"hanja": "士", "hangul": "사", "strokes": 3,  "element": "토", "meaning": "선비"},
    {"hanja": "君", "hangul": "군", "strokes": 7,  "element": "토", "meaning": "임금, 군자"},
    {"hanja": "王", "hangul": "왕", "strokes": 4,  "element": "토", "meaning": "임금"},
    {"hanja": "帝", "hangul": "제", "strokes": 9,  "element": "토", "meaning": "임금"},
    {"hanja": "皇", "hangul": "황", "strokes": 12, "element": "토", "meaning": "임금"},
    {"hanja": "聖", "hangul": "성", "strokes": 13, "element": "토", "meaning": "성인"},
    {"hanja": "賢", "hangul": "현", "strokes": 15, "element": "토", "meaning": "어질다"},
    {"hanja": "良", "hangul": "량", "strokes": 7,  "element": "토", "meaning": "어질다, 좋다"},
    {"hanja": "淳", "hangul": "순", "strokes": 12, "element": "토", "meaning": "순박하다"},
    {"hanja": "朴", "hangul": "박", "strokes": 6,  "element": "토", "meaning": "순박하다"},
    {"hanja": "誠", "hangul": "성", "strokes": 14, "element": "토", "meaning": "정성"},
    {"hanja": "忠", "hangul": "충", "strokes": 8,  "element": "토", "meaning": "충성"},
    {"hanja": "孝", "hangul": "효", "strokes": 7,  "element": "토", "meaning": "효도"},
    {"hanja": "悌", "hangul": "제", "strokes": 10, "element": "토", "meaning": "공손하다"},
    {"hanja": "仁", "hangul": "인", "strokes": 4,  "element": "토", "meaning": "어질다"},
    {"hanja": "義", "hangul": "의", "strokes": 13, "element": "토", "meaning": "의롭다"},
    {"hanja": "禮", "hangul": "례", "strokes": 18, "element": "토", "meaning": "예도"},
    {"hanja": "智", "hangul": "지", "strokes": 12, "element": "토", "meaning": "지혜"},
    {"hanja": "信", "hangul": "신", "strokes": 9,  "element": "토", "meaning": "믿음"},
    {"hanja": "庸", "hangul": "용", "strokes": 11, "element": "토", "meaning": "평상, 쓰다"},
    {"hanja": "中", "hangul": "중", "strokes": 4,  "element": "토", "meaning": "가운데"},
    {"hanja": "和", "hangul": "화", "strokes": 8,  "element": "토", "meaning": "화목하다"},
    {"hanja": "同", "hangul": "동", "strokes": 6,  "element": "토", "meaning": "같다"},
    {"hanja": "共", "hangul": "공", "strokes": 6,  "element": "토", "meaning": "함께"},
    {"hanja": "合", "hangul": "합", "strokes": 6,  "element": "토", "meaning": "합하다"},
    {"hanja": "聚", "hangul": "취", "strokes": 14, "element": "토", "meaning": "모이다"},
    {"hanja": "集", "hangul": "집", "strokes": 12, "element": "토", "meaning": "모이다"},
    {"hanja": "統", "hangul": "통", "strokes": 12, "element": "토", "meaning": "거느리다"},
    {"hanja": "領", "hangul": "령", "strokes": 14, "element": "토", "meaning": "거느리다"},
    {"hanja": "率", "hangul": "솔", "strokes": 11, "element": "토", "meaning": "거느리다"},
    {"hanja": "帥", "hangul": "수", "strokes": 9,  "element": "토", "meaning": "장수"},
    {"hanja": "將", "hangul": "장", "strokes": 11, "element": "토", "meaning": "장수"},
    {"hanja": "相", "hangul": "상", "strokes": 9,  "element": "토", "meaning": "재상"},
    {"hanja": "宰", "hangul": "재", "strokes": 10, "element": "토", "meaning": "재상"},
    {"hanja": "政", "hangul": "정", "strokes": 9,  "element": "토", "meaning": "정치"},
    {"hanja": "治", "hangul": "치", "strokes": 9,  "element": "토", "meaning": "다스리다"},
    {"hanja": "國", "hangul": "국", "strokes": 11, "element": "토", "meaning": "나라"},
    {"hanja": "邦", "hangul": "방", "strokes": 7,  "element": "토", "meaning": "나라"},
    {"hanja": "民", "hangul": "민", "strokes": 5,  "element": "토", "meaning": "백성"},
    {"hanja": "衆", "hangul": "중", "strokes": 12, "element": "토", "meaning": "무리"},
    {"hanja": "群", "hangul": "군", "strokes": 13, "element": "토", "meaning": "무리"},

    # ── 금(金) 오행 ──────────────────────────────
    {"hanja": "金", "hangul": "금", "strokes": 8,  "element": "금", "meaning": "금, 쇠"},
    {"hanja": "銀", "hangul": "은", "strokes": 14, "element": "금", "meaning": "은"},
    {"hanja": "銅", "hangul": "동", "strokes": 14, "element": "금", "meaning": "구리"},
    {"hanja": "鐵", "hangul": "철", "strokes": 21, "element": "금", "meaning": "쇠"},
    {"hanja": "鋼", "hangul": "강", "strokes": 16, "element": "금", "meaning": "강철"},
    {"hanja": "鑄", "hangul": "주", "strokes": 22, "element": "금", "meaning": "주조하다"},
    {"hanja": "鍊", "hangul": "련", "strokes": 17, "element": "금", "meaning": "단련하다"},
    {"hanja": "錦", "hangul": "금", "strokes": 16, "element": "금", "meaning": "비단"},
    {"hanja": "鎬", "hangul": "호", "strokes": 18, "element": "금", "meaning": "호경(지명)"},
    {"hanja": "鏡", "hangul": "경", "strokes": 19, "element": "금", "meaning": "거울"},
    {"hanja": "鐘", "hangul": "종", "strokes": 20, "element": "금", "meaning": "종"},
    {"hanja": "鈴", "hangul": "령", "strokes": 13, "element": "금", "meaning": "방울"},
    {"hanja": "錫", "hangul": "석", "strokes": 16, "element": "금", "meaning": "주석"},
    {"hanja": "鑫", "hangul": "흠", "strokes": 24, "element": "금", "meaning": "금이 많다"},
    {"hanja": "玉", "hangul": "옥", "strokes": 5,  "element": "금", "meaning": "옥"},
    {"hanja": "珍", "hangul": "진", "strokes": 9,  "element": "금", "meaning": "보배"},
    {"hanja": "珠", "hangul": "주", "strokes": 10, "element": "금", "meaning": "구슬"},
    {"hanja": "璋", "hangul": "장", "strokes": 15, "element": "금", "meaning": "홀"},
    {"hanja": "璃", "hangul": "리", "strokes": 15, "element": "금", "meaning": "유리"},
    {"hanja": "瑩", "hangul": "영", "strokes": 15, "element": "금", "meaning": "옥빛"},
    {"hanja": "瑾", "hangul": "근", "strokes": 15, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "璿", "hangul": "선", "strokes": 18, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "琮", "hangul": "종", "strokes": 12, "element": "금", "meaning": "옥기"},
    {"hanja": "琛", "hangul": "침", "strokes": 12, "element": "금", "meaning": "보배"},
    {"hanja": "琦", "hangul": "기", "strokes": 12, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "琬", "hangul": "완", "strokes": 12, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "琳", "hangul": "림", "strokes": 12, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "瑀", "hangul": "우", "strokes": 13, "element": "금", "meaning": "옥"},
    {"hanja": "瑜", "hangul": "유", "strokes": 13, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "瑗", "hangul": "원", "strokes": 13, "element": "금", "meaning": "큰 구슬"},
    {"hanja": "瑛", "hangul": "영", "strokes": 13, "element": "금", "meaning": "옥빛"},
    {"hanja": "瑞", "hangul": "서", "strokes": 13, "element": "금", "meaning": "상서롭다"},
    {"hanja": "瑰", "hangul": "괴", "strokes": 14, "element": "금", "meaning": "아름다운 옥"},
    {"hanja": "璞", "hangul": "박", "strokes": 16, "element": "금", "meaning": "원석"},
    {"hanja": "璘", "hangul": "린", "strokes": 16, "element": "금", "meaning": "옥빛"},
    {"hanja": "璟", "hangul": "경", "strokes": 16, "element": "금", "meaning": "옥빛"},
    {"hanja": "璨", "hangul": "찬", "strokes": 17, "element": "금", "meaning": "옥빛"},
    {"hanja": "璩", "hangul": "거", "strokes": 17, "element": "금", "meaning": "옥 귀걸이"},
    {"hanja": "石", "hangul": "석", "strokes": 5,  "element": "금", "meaning": "돌"},
    {"hanja": "磐", "hangul": "반", "strokes": 15, "element": "금", "meaning": "큰 바위"},
    {"hanja": "碩", "hangul": "석", "strokes": 14, "element": "금", "meaning": "크다"},
    {"hanja": "礎", "hangul": "초", "strokes": 18, "element": "금", "meaning": "주춧돌"},
    {"hanja": "磊", "hangul": "뢰", "strokes": 15, "element": "금", "meaning": "돌이 많다"},
    {"hanja": "岩", "hangul": "암", "strokes": 8,  "element": "금", "meaning": "바위"},
    {"hanja": "巖", "hangul": "암", "strokes": 23, "element": "금", "meaning": "바위"},
    {"hanja": "鑛", "hangul": "광", "strokes": 23, "element": "금", "meaning": "광석"},
    {"hanja": "礦", "hangul": "광", "strokes": 20, "element": "금", "meaning": "광석"},
    {"hanja": "西", "hangul": "서", "strokes": 6,  "element": "금", "meaning": "서쪽"},
    {"hanja": "秋", "hangul": "추", "strokes": 9,  "element": "금", "meaning": "가을"},
    {"hanja": "義", "hangul": "의", "strokes": 13, "element": "금", "meaning": "의롭다"},
    {"hanja": "勇", "hangul": "용", "strokes": 9,  "element": "금", "meaning": "용감하다"},
    {"hanja": "毅", "hangul": "의", "strokes": 15, "element": "금", "meaning": "굳세다"},
    {"hanja": "剛", "hangul": "강", "strokes": 10, "element": "금", "meaning": "굳세다"},
    {"hanja": "堅", "hangul": "견", "strokes": 11, "element": "금", "meaning": "굳다"},
    {"hanja": "鋒", "hangul": "봉", "strokes": 15, "element": "금", "meaning": "날카롭다"},
    {"hanja": "銳", "hangul": "예", "strokes": 15, "element": "금", "meaning": "날카롭다"},
    {"hanja": "利", "hangul": "리", "strokes": 7,  "element": "금", "meaning": "날카롭다, 이롭다"},
    {"hanja": "鋭", "hangul": "예", "strokes": 15, "element": "금", "meaning": "날카롭다"},
    {"hanja": "鎭", "hangul": "진", "strokes": 18, "element": "금", "meaning": "진압하다, 진정하다"},
    {"hanja": "鎧", "hangul": "개", "strokes": 18, "element": "금", "meaning": "갑옷"},
    {"hanja": "鎔", "hangul": "용", "strokes": 18, "element": "금", "meaning": "녹이다"},
    {"hanja": "鍾", "hangul": "종", "strokes": 17, "element": "금", "meaning": "종"},
    {"hanja": "鑑", "hangul": "감", "strokes": 22, "element": "금", "meaning": "거울, 감별하다"},
    {"hanja": "鑰", "hangul": "약", "strokes": 25, "element": "금", "meaning": "열쇠"},
    {"hanja": "鑿", "hangul": "착", "strokes": 28, "element": "금", "meaning": "뚫다"},
    {"hanja": "鑲", "hangul": "양", "strokes": 25, "element": "금", "meaning": "끼우다"},
    {"hanja": "鑣", "hangul": "표", "strokes": 25, "element": "금", "meaning": "재갈"},
    {"hanja": "鑪", "hangul": "로", "strokes": 25, "element": "금", "meaning": "화로"},
    {"hanja": "鑰", "hangul": "약", "strokes": 25, "element": "금", "meaning": "열쇠"},
    {"hanja": "鑷", "hangul": "섭", "strokes": 26, "element": "금", "meaning": "족집게"},
    {"hanja": "鑸", "hangul": "루", "strokes": 26, "element": "금", "meaning": "도끼"},
    {"hanja": "鑹", "hangul": "찬", "strokes": 27, "element": "금", "meaning": "창"},
    {"hanja": "鑺", "hangul": "과", "strokes": 27, "element": "금", "meaning": "낫"},
    {"hanja": "鑻", "hangul": "반", "strokes": 27, "element": "금", "meaning": "쟁반"},
    {"hanja": "鑼", "hangul": "라", "strokes": 27, "element": "금", "meaning": "징"},
    {"hanja": "鑽", "hangul": "찬", "strokes": 27, "element": "금", "meaning": "뚫다"},
    {"hanja": "鑾", "hangul": "란", "strokes": 27, "element": "금", "meaning": "방울"},
    {"hanja": "鑿", "hangul": "착", "strokes": 28, "element": "금", "meaning": "뚫다"},

    # ── 수(水) 오행 ──────────────────────────────
    {"hanja": "水", "hangul": "수", "strokes": 4,  "element": "수", "meaning": "물"},
    {"hanja": "海", "hangul": "해", "strokes": 10, "element": "수", "meaning": "바다"},
    {"hanja": "江", "hangul": "강", "strokes": 7,  "element": "수", "meaning": "강"},
    {"hanja": "河", "hangul": "하", "strokes": 9,  "element": "수", "meaning": "강"},
    {"hanja": "湖", "hangul": "호", "strokes": 12, "element": "수", "meaning": "호수"},
    {"hanja": "川", "hangul": "천", "strokes": 3,  "element": "수", "meaning": "내"},
    {"hanja": "溪", "hangul": "계", "strokes": 13, "element": "수", "meaning": "시내"},
    {"hanja": "泉", "hangul": "천", "strokes": 9,  "element": "수", "meaning": "샘"},
    {"hanja": "源", "hangul": "원", "strokes": 13, "element": "수", "meaning": "근원"},
    {"hanja": "流", "hangul": "류", "strokes": 10, "element": "수", "meaning": "흐르다"},
    {"hanja": "波", "hangul": "파", "strokes": 9,  "element": "수", "meaning": "물결"},
    {"hanja": "瀾", "hangul": "란", "strokes": 20, "element": "수", "meaning": "물결"},
    {"hanja": "潮", "hangul": "조", "strokes": 15, "element": "수", "meaning": "조수"},
    {"hanja": "浪", "hangul": "랑", "strokes": 10, "element": "수", "meaning": "물결"},
    {"hanja": "涌", "hangul": "용", "strokes": 11, "element": "수", "meaning": "솟아오르다"},
    {"hanja": "湧", "hangul": "용", "strokes": 12, "element": "수", "meaning": "솟아오르다"},
    {"hanja": "澄", "hangul": "징", "strokes": 16, "element": "수", "meaning": "맑다"},
    {"hanja": "清", "hangul": "청", "strokes": 11, "element": "수", "meaning": "맑다"},
    {"hanja": "淸", "hangul": "청", "strokes": 12, "element": "수", "meaning": "맑다"},
    {"hanja": "潔", "hangul": "결", "strokes": 16, "element": "수", "meaning": "깨끗하다"},
    {"hanja": "洋", "hangul": "양", "strokes": 9,  "element": "수", "meaning": "큰 바다"},
    {"hanja": "洪", "hangul": "홍", "strokes": 10, "element": "수", "meaning": "넓다, 큰 물"},
    {"hanja": "浩", "hangul": "호", "strokes": 11, "element": "수", "meaning": "넓다"},
    {"hanja": "淵", "hangul": "연", "strokes": 12, "element": "수", "meaning": "깊은 못"},
    {"hanja": "深", "hangul": "심", "strokes": 12, "element": "수", "meaning": "깊다"},
    {"hanja": "潤", "hangul": "윤", "strokes": 16, "element": "수", "meaning": "윤택하다"},
    {"hanja": "澤", "hangul": "택", "strokes": 17, "element": "수", "meaning": "못, 은택"},
    {"hanja": "沛", "hangul": "패", "strokes": 8,  "element": "수", "meaning": "넘치다"},
    {"hanja": "汎", "hangul": "범", "strokes": 7,  "element": "수", "meaning": "넓다"},
    {"hanja": "泓", "hangul": "홍", "strokes": 9,  "element": "수", "meaning": "깊고 넓다"},
    {"hanja": "洵", "hangul": "순", "strokes": 10, "element": "수", "meaning": "참으로"},
    {"hanja": "浚", "hangul": "준", "strokes": 10, "element": "수", "meaning": "깊다"},
    {"hanja": "涵", "hangul": "함", "strokes": 12, "element": "수", "meaning": "담그다"},
    {"hanja": "渙", "hangul": "환", "strokes": 13, "element": "수", "meaning": "흩어지다"},
    {"hanja": "溶", "hangul": "용", "strokes": 13, "element": "수", "meaning": "녹다"},
    {"hanja": "滔", "hangul": "도", "strokes": 14, "element": "수", "meaning": "넘치다"},
    {"hanja": "漢", "hangul": "한", "strokes": 14, "element": "수", "meaning": "한수, 한나라"},
    {"hanja": "漸", "hangul": "점", "strokes": 15, "element": "수", "meaning": "점점"},
    {"hanja": "澔", "hangul": "호", "strokes": 16, "element": "수", "meaning": "넓다"},
    {"hanja": "濬", "hangul": "준", "strokes": 17, "element": "수", "meaning": "깊다"},
    {"hanja": "濤", "hangul": "도", "strokes": 17, "element": "수", "meaning": "큰 물결"},
    {"hanja": "瀚", "hangul": "한", "strokes": 20, "element": "수", "meaning": "넓다"},
    {"hanja": "瀛", "hangul": "영", "strokes": 20, "element": "수", "meaning": "큰 바다"},
    {"hanja": "雨", "hangul": "우", "strokes": 8,  "element": "수", "meaning": "비"},
    {"hanja": "霖", "hangul": "림", "strokes": 16, "element": "수", "meaning": "장마"},
    {"hanja": "露", "hangul": "로", "strokes": 21, "element": "수", "meaning": "이슬"},
    {"hanja": "霞", "hangul": "하", "strokes": 17, "element": "수", "meaning": "노을"},
    {"hanja": "雲", "hangul": "운", "strokes": 12, "element": "수", "meaning": "구름"},
    {"hanja": "霽", "hangul": "제", "strokes": 22, "element": "수", "meaning": "개다"},
    {"hanja": "北", "hangul": "북", "strokes": 5,  "element": "수", "meaning": "북쪽"},
    {"hanja": "冬", "hangul": "동", "strokes": 5,  "element": "수", "meaning": "겨울"},
    {"hanja": "智", "hangul": "지", "strokes": 12, "element": "수", "meaning": "지혜"},
    {"hanja": "謀", "hangul": "모", "strokes": 16, "element": "수", "meaning": "꾀하다"},
    {"hanja": "策", "hangul": "책", "strokes": 12, "element": "수", "meaning": "꾀, 계획"},
    {"hanja": "計", "hangul": "계", "strokes": 9,  "element": "수", "meaning": "꾀하다"},
    {"hanja": "算", "hangul": "산", "strokes": 14, "element": "수", "meaning": "셈하다"},
    {"hanja": "籌", "hangul": "주", "strokes": 20, "element": "수", "meaning": "꾀하다"},
    {"hanja": "慮", "hangul": "려", "strokes": 15, "element": "수", "meaning": "생각하다"},
    {"hanja": "思", "hangul": "사", "strokes": 9,  "element": "수", "meaning": "생각하다"},
    {"hanja": "念", "hangul": "념", "strokes": 8,  "element": "수", "meaning": "생각하다"},
    {"hanja": "想", "hangul": "상", "strokes": 13, "element": "수", "meaning": "생각하다"},
    {"hanja": "惟", "hangul": "유", "strokes": 11, "element": "수", "meaning": "생각하다"},
    {"hanja": "維", "hangul": "유", "strokes": 14, "element": "수", "meaning": "묶다, 유지하다"},
    {"hanja": "綱", "hangul": "강", "strokes": 14, "element": "수", "meaning": "벼리"},
    {"hanja": "紀", "hangul": "기", "strokes": 9,  "element": "수", "meaning": "벼리, 기록"},
    {"hanja": "倫", "hangul": "륜", "strokes": 10, "element": "수", "meaning": "인륜"},
    {"hanja": "理", "hangul": "리", "strokes": 11, "element": "수", "meaning": "이치"},
    {"hanja": "哲", "hangul": "철", "strokes": 10, "element": "수", "meaning": "밝고 슬기롭다"},
    {"hanja": "睿", "hangul": "예", "strokes": 14, "element": "수", "meaning": "슬기롭다"},
    {"hanja": "慧", "hangul": "혜", "strokes": 15, "element": "수", "meaning": "슬기롭다"},
    {"hanja": "聰", "hangul": "총", "strokes": 17, "element": "수", "meaning": "총명하다"},
    {"hanja": "穎", "hangul": "영", "strokes": 16, "element": "수", "meaning": "뛰어나다"},
    {"hanja": "俊", "hangul": "준", "strokes": 9,  "element": "수", "meaning": "준수하다"},
    {"hanja": "傑", "hangul": "걸", "strokes": 12, "element": "수", "meaning": "뛰어나다"},
    {"hanja": "秀", "hangul": "수", "strokes": 7,  "element": "수", "meaning": "빼어나다"},
    {"hanja": "英", "hangul": "영", "strokes": 9,  "element": "수", "meaning": "꽃부리, 영웅"},
    {"hanja": "豪", "hangul": "호", "strokes": 14, "element": "수", "meaning": "호걸"},
    {"hanja": "傑", "hangul": "걸", "strokes": 12, "element": "수", "meaning": "뛰어나다"},
    {"hanja": "奇", "hangul": "기", "strokes": 8,  "element": "수", "meaning": "기이하다"},
    {"hanja": "異", "hangul": "이", "strokes": 11, "element": "수", "meaning": "다르다"},
    {"hanja": "特", "hangul": "특", "strokes": 10, "element": "수", "meaning": "특별하다"},
    {"hanja": "卓", "hangul": "탁", "strokes": 8,  "element": "수", "meaning": "뛰어나다"},
    {"hanja": "越", "hangul": "월", "strokes": 12, "element": "수", "meaning": "넘다, 뛰어나다"},
    {"hanja": "超", "hangul": "초", "strokes": 12, "element": "수", "meaning": "넘다"},
    {"hanja": "絶", "hangul": "절", "strokes": 12, "element": "수", "meaning": "끊다, 뛰어나다"},
    {"hanja": "冠", "hangul": "관", "strokes": 9,  "element": "수", "meaning": "으뜸"},
    {"hanja": "魁", "hangul": "괴", "strokes": 14, "element": "수", "meaning": "으뜸"},
    {"hanja": "首", "hangul": "수", "strokes": 9,  "element": "수", "meaning": "머리, 으뜸"},
    {"hanja": "元", "hangul": "원", "strokes": 4,  "element": "수", "meaning": "으뜸"},
    {"hanja": "冀", "hangul": "기", "strokes": 16, "element": "수", "meaning": "바라다"},
    {"hanja": "渴", "hangul": "갈", "strokes": 13, "element": "수", "meaning": "목마르다, 간절히 바라다"},
    {"hanja": "沃", "hangul": "옥", "strokes": 8,  "element": "수", "meaning": "기름지다"},
    {"hanja": "泰", "hangul": "태", "strokes": 10, "element": "수", "meaning": "크다, 평안하다"},
    {"hanja": "浦", "hangul": "포", "strokes": 10, "element": "수", "meaning": "포구"},
    {"hanja": "港", "hangul": "항", "strokes": 12, "element": "수", "meaning": "항구"},
    {"hanja": "灣", "hangul": "만", "strokes": 25, "element": "수", "meaning": "만(灣)"},
    {"hanja": "洲", "hangul": "주", "strokes": 10, "element": "수", "meaning": "섬, 대륙"},
    {"hanja": "渚", "hangul": "저", "strokes": 12, "element": "수", "meaning": "물가"},
    {"hanja": "汀", "hangul": "정", "strokes": 6,  "element": "수", "meaning": "물가"},
    {"hanja": "沙", "hangul": "사", "strokes": 8,  "element": "수", "meaning": "모래"},
    {"hanja": "洛", "hangul": "락", "strokes": 10, "element": "수", "meaning": "낙수(강 이름)"},
    {"hanja": "渭", "hangul": "위", "strokes": 13, "element": "수", "meaning": "위수(강 이름)"},
    {"hanja": "汝", "hangul": "여", "strokes": 7,  "element": "수", "meaning": "너, 여수(강 이름)"},
    {"hanja": "沂", "hangul": "기", "strokes": 8,  "element": "수", "meaning": "기수(강 이름)"},
    {"hanja": "汶", "hangul": "문", "strokes": 8,  "element": "수", "meaning": "문수(강 이름)"},
    {"hanja": "沔", "hangul": "면", "strokes": 8,  "element": "수", "meaning": "면수(강 이름)"},
    {"hanja": "洞", "hangul": "동", "strokes": 10, "element": "수", "meaning": "골짜기"},
    {"hanja": "淮", "hangul": "회", "strokes": 12, "element": "수", "meaning": "회수(강 이름)"},
    {"hanja": "渾", "hangul": "혼", "strokes": 13, "element": "수", "meaning": "흐리다"},
    {"hanja": "滋", "hangul": "자", "strokes": 13, "element": "수", "meaning": "불다, 자라다"},
    {"hanja": "漣", "hangul": "련", "strokes": 15, "element": "수", "meaning": "잔물결"},
    {"hanja": "漪", "hangul": "의", "strokes": 15, "element": "수", "meaning": "잔물결"},
    {"hanja": "潺", "hangul": "잔", "strokes": 15, "element": "수", "meaning": "물 흐르는 소리"},
    {"hanja": "澗", "hangul": "간", "strokes": 16, "element": "수", "meaning": "산골짜기 물"},
    {"hanja": "瀑", "hangul": "폭", "strokes": 19, "element": "수", "meaning": "폭포"},
    {"hanja": "瀏", "hangul": "류", "strokes": 19, "element": "수", "meaning": "맑고 깊다"},
    {"hanja": "瀟", "hangul": "소", "strokes": 19, "element": "수", "meaning": "맑고 깊다"},
    {"hanja": "瀰", "hangul": "미", "strokes": 20, "element": "수", "meaning": "넘치다"},
    {"hanja": "灝", "hangul": "호", "strokes": 21, "element": "수", "meaning": "넓다"},
    {"hanja": "灑", "hangul": "쇄", "strokes": 22, "element": "수", "meaning": "뿌리다"},
    {"hanja": "灌", "hangul": "관", "strokes": 22, "element": "수", "meaning": "물 대다"},
    {"hanja": "灘", "hangul": "탄", "strokes": 22, "element": "수", "meaning": "여울"},
    {"hanja": "灣", "hangul": "만", "strokes": 25, "element": "수", "meaning": "만(灣)"},
]


def insert_batch(records: list, batch_size: int = 500) -> None:
    """Supabase REST API를 통해 한자 데이터를 배치 삽입"""
    url = f"{SUPABASE_URL}/rest/v1/hanja_dictionary"
    total = len(records)
    
    for i in range(0, total, batch_size):
        batch = records[i:i + batch_size]
        resp = requests.post(url, headers=HEADERS, json=batch)
        
        if resp.status_code in (200, 201):
            print(f"  ✅ {i + len(batch)}/{total} 삽입 완료")
        else:
            print(f"  ❌ 오류 ({resp.status_code}): {resp.text[:200]}")
            raise RuntimeError(f"Supabase insert failed: {resp.status_code}")
        
        time.sleep(0.3)  # Rate limit 방지


def check_existing_count() -> int:
    """기존 데이터 수 확인"""
    url = f"{SUPABASE_URL}/rest/v1/hanja_dictionary?select=id"
    headers = {**HEADERS, "Prefer": "count=exact", "Range": "0-0"}
    resp = requests.get(url, headers=headers)
    
    content_range = resp.headers.get("Content-Range", "*/0")
    total = content_range.split("/")[-1]
    return int(total) if total.isdigit() else 0


def main():
    if not SUPABASE_SERVICE_KEY:
        print("❌ SUPABASE_SERVICE_KEY 환경변수를 설정해주세요.")
        print("   Supabase 대시보드 > Settings > API > service_role key")
        return

    print(f"🔍 기존 데이터 확인 중...")
    existing = check_existing_count()
    print(f"   기존 레코드 수: {existing}")

    if existing > 0:
        print(f"⚠️  이미 {existing}개의 데이터가 있습니다. 중복 삽입을 건너뜁니다.")
        print("   전체 재삽입이 필요하면 Supabase 대시보드에서 테이블을 비운 후 재실행하세요.")
        return

    # 중복 제거 (hanja 기준)
    seen = set()
    unique_data = []
    for row in HANJA_DATA:
        key = row["hanja"]
        if key not in seen:
            seen.add(key)
            unique_data.append(row)

    print(f"📦 총 {len(unique_data)}개 한자 데이터 삽입 시작...")
    insert_batch(unique_data)
    print(f"✅ 완료! {len(unique_data)}개 한자 데이터가 Supabase에 저장되었습니다.")
    print()
    print("📋 다음 단계:")
    print("   1. Supabase 대시보드에서 데이터 확인")
    print("   2. 전체 5,382자 데이터가 필요한 경우 CSV 파일로 추가 삽입 필요")


if __name__ == "__main__":
    main()
